name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-41.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.0.0
  go_router: ^13.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: "^0.13.1"
  introduction_screen: ^3.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/todologo.png"
#   min_sdk_android: 21
#   adaptive_icon_background: "#FFFFFF"
#   # adaptive_icon_foreground: "assets/icons/todologo_foreground.png"
#   web:
#     generate: true
#     background_color: "#2d2d2d"
#   windows:
#     generate: true
#     icon_size: 48
#   macos:
#     generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/todologo.png